package rcrsystem.presentation.view;

import Modelo.Proveedor;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import rcrsystem.presentation.controller.Ag_Ed_Proveedor_Controlador;
import rcrsystem.presentation.model.Proveedor_Modelo;

public class VentanaProveedor extends javax.swing.JDialog implements java.util.Observer {

    Ag_Ed_Proveedor_Controlador controlador;
    Proveedor_Modelo modelo;
    public static Border BORDER_ERROR = BorderFactory.createLineBorder(Color.red);
    public Border BORDER_NOBORDER;

    public VentanaProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/rcrsystem/presentation/view/iconos/logoRCR.png")).getImage());
        setLocationRelativeTo(null);
        BORDER_NOBORDER = this.jTextField_nombre.getBorder();
    }

    public Ag_Ed_Proveedor_Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Ag_Ed_Proveedor_Controlador controlador) {
        this.controlador = controlador;
    }

    public Proveedor_Modelo getModelo() {
        return modelo;
    }

    public void setModelo(Proveedor_Modelo modelo) {
        this.modelo = modelo;
        modelo.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_lugar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jButton_accion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_telFijo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_telCelular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Contacto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Adminstrar Usuario");

        jLabel1.setText("Cédula");

        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });
        jTextField_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_idKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Lugar:");

        jTextField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyTyped(evt);
            }
        });

        jTextField_lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lugarActionPerformed(evt);
            }
        });
        jTextField_lugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_lugarKeyTyped(evt);
            }
        });

        jButton_accion.setText("Agregar");
        jButton_accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_accionActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Teléfono Fijo:");

        jTextField_telFijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_telFijoKeyTyped(evt);
            }
        });

        jLabel6.setText("Teléfono Celular:");

        jTextField_telCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telCelularActionPerformed(evt);
            }
        });
        jTextField_telCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_telCelularKeyTyped(evt);
            }
        });

        jLabel4.setText("Persona Contacto:");

        jTextField_Contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ContactoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombre)
                            .addComponent(jTextField_lugar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_telFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_telCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton_accion)
                .addGap(95, 95, 95)
                .addComponent(jButton2)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_telFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_telCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton_accion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_accionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_accionActionPerformed
        this.jButton_accion.setEnabled(false);
        controlador.agregar();
        this.jButton_accion.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton_accionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jButton2.setEnabled(false);
        this.setVisible(false);
        this.jButton2.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idKeyTyped
       if (this.jTextField_id.getText().length() > 37) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
       }         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idKeyTyped

    private void jTextField_lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lugarActionPerformed

    private void jTextField_lugarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_lugarKeyTyped
    if (this.jTextField_lugar.getText().length() > 100) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }         
    }//GEN-LAST:event_jTextField_lugarKeyTyped

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jTextField_telCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telCelularKeyTyped
        if (this.jTextField_telCelular.getText().length() < 9) {
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        }
        else{
         Toolkit.getDefaultToolkit().beep();
            evt.consume();
        } 
        
    }//GEN-LAST:event_jTextField_telCelularKeyTyped

    private void jTextField_telFijoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telFijoKeyTyped
       if (this.jTextField_telFijo.getText().length() < 9){ 
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            }
       }
        else{
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_telFijoKeyTyped

    private void jTextField_telCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telCelularActionPerformed
        
    }//GEN-LAST:event_jTextField_telCelularActionPerformed

    private void jTextField_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyTyped
        if (this.jTextField_nombre.getText().length() > 70) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreKeyTyped

    private void jTextField_ContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ContactoKeyTyped
        if (this.jTextField_Contacto.getText().length() > 70) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_ContactoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton_accion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField jTextField_Contacto;
    public javax.swing.JTextField jTextField_id;
    public javax.swing.JTextField jTextField_lugar;
    public javax.swing.JTextField jTextField_nombre;
    public javax.swing.JTextField jTextField_telCelular;
    public javax.swing.JTextField jTextField_telFijo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(java.util.Observable updatedModel, Object parametros) {
        if (parametros != Proveedor_Modelo.ae_usuario_actual) {
            return;
        }
        Proveedor usuarioCurrent = modelo.obtener_proveedor_actual();
        if (usuarioCurrent == null) {
            this.jTextField_id.setText("");
            this.jTextField_nombre.setText("");
            this.jTextField_lugar.setText("");
            this.jTextField_Contacto.setText("");
            this.jTextField_telCelular.setText("");
            this.jTextField_telFijo.setText("");
        } else {
            this.jTextField_id.setText(usuarioCurrent.obtener_codigo());
            if (modelo.obtener_errores().get("id") != null) {
                this.jTextField_id.setBorder(BORDER_ERROR);
                this.jTextField_id.setToolTipText(modelo.obtener_errores().get("id"));
            } else {
                this.jTextField_id.setBorder(BORDER_NOBORDER);
                this.jTextField_id.setToolTipText(null);
            }
            this.jTextField_nombre.setText(usuarioCurrent.obtener_nombre());
            if (modelo.obtener_errores().get("nombre") != null) {
                this.jTextField_nombre.setBorder(BORDER_ERROR);
                this.jTextField_nombre.setToolTipText(modelo.obtener_errores().get("nombre"));
            } else {
                this.jTextField_nombre.setBorder(BORDER_NOBORDER);
                this.jTextField_nombre.setToolTipText(null);
            }
            this.jTextField_lugar.setText(usuarioCurrent.obtener_lugar());
            if (modelo.obtener_errores().get("lugar") != null) {
                this.jTextField_lugar.setBorder(BORDER_ERROR);
                this.jTextField_lugar.setToolTipText(modelo.obtener_errores().get("lugar"));
            } else {
                this.jTextField_lugar.setBorder(BORDER_NOBORDER);
                this.jTextField_lugar.setToolTipText(null);
            }
            this.jTextField_Contacto.setText(usuarioCurrent.obtener_personaContacto());
            if (modelo.obtener_errores().get("contacto") != null) {
                this.jTextField_Contacto.setBorder(BORDER_ERROR);
                this.jTextField_Contacto.setToolTipText(modelo.obtener_errores().get("contacto"));
            } else {
                this.jTextField_Contacto.setBorder(BORDER_NOBORDER);
                this.jTextField_Contacto.setToolTipText(null);
            }
            if(usuarioCurrent.obtener_telCelular()==0 && modelo.obtener_modo()!=rcrsystem.Aplicacion.ae_modo_editar){
             this.jTextField_telCelular.setText("");
            }else{
            this.jTextField_telCelular.setText(Integer.toString(usuarioCurrent.obtener_telCelular()));
            }
            if (modelo.obtener_errores().get("celular") != null) {
                this.jTextField_telCelular.setBorder(BORDER_ERROR);
                this.jTextField_telCelular.setToolTipText(modelo.obtener_errores().get("celular"));
            } else {
                this.jTextField_telCelular.setBorder(BORDER_NOBORDER);
                this.jTextField_telCelular.setToolTipText(null);
            }
            if(usuarioCurrent.obtener_telFijo()==0 && modelo.obtener_modo()!=rcrsystem.Aplicacion.ae_modo_editar){
             this.jTextField_telFijo.setText("");
            }else{
            this.jTextField_telFijo.setText(Integer.toString(usuarioCurrent.obtener_telFijo()));
            }
            if (modelo.obtener_errores().get("fijo") != null) {
                this.jTextField_telFijo.setBorder(BORDER_ERROR);
                this.jTextField_telFijo.setToolTipText(modelo.obtener_errores().get("fijo"));
            } else {
                this.jTextField_telFijo.setBorder(BORDER_NOBORDER);
                this.jTextField_telFijo.setToolTipText(null);
            }

          
        }
        this.validate();
        if (modelo.obtener_mensaje() != null) {
            if (!modelo.obtener_mensaje().equals("")) {
                JOptionPane.showMessageDialog(this, modelo.obtener_mensaje(), "", JOptionPane.INFORMATION_MESSAGE);
                modelo.colocar_mensaje("");
            }
        }
    }
}
